[tool.ruff]
line-length = 79
lint.ignore = ["F401"]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
docstring-code-format = true
docstring-code-line-length = 72
indent-style = "space"
