[tool.ruff]
# Set the maximum line length to 120.
line-length = 120

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
